### ISSUE TITLE
1

### ISSUE THREAD

**Issue by h2e8c6g4x2** [h2e8c6g4x2/p2de#1]
![row-1-col-1](https://user-images.githubusercontent.com/31631915/30037080-243a6fdc-91c1-11e7-9aa3-8456db34614c.jpg)
![row-1-col-2](https://user-images.githubusercontent.com/31631915/30037081-243b6004-91c1-11e7-8cab-96bbbbcce065.jpg)
![row-1-col-3](https://user-images.githubusercontent.com/31631915/30037082-243d6066-91c1-11e7-99c6-152b77f3a618.jpg)
![row-1-col-4](https://user-images.githubusercontent.com/31631915/30037083-243ef32c-91c1-11e7-9427-414dc0ad70b5.jpg)
![row-1-col-5](https://user-images.githubusercontent.com/31631915/30037085-24402ecc-91c1-11e7-8aac-8beb43ff83b5.jpg)
![row-1-col-6](https://user-images.githubusercontent.com/31631915/30037086-24406f22-91c1-11e7-9c1d-fa6bfae73474.jpg)
![row-1-col-7](https://user-images.githubusercontent.com/31631915/30037087-2457a642-91c1-11e7-8987-5fbdb73ee430.jpg)
![row-1-col-8](https://user-images.githubusercontent.com/31631915/30037088-2457e102-91c1-11e7-9366-2ab30a022c1c.jpg)
![row-1-col-9](https://user-images.githubusercontent.com/31631915/30037089-245a1544-91c1-11e7-874a-395008c97232.jpg)
![row-1-col-10](https://user-images.githubusercontent.com/31631915/30037090-245c2686-91c1-11e7-9eb4-3388e21494a9.jpg)
![row-2-col-1](https://user-images.githubusercontent.com/31631915/30037091-245e0c6c-91c1-11e7-9012-18c19b35a81b.jpg)
![row-2-col-2](https://user-images.githubusercontent.com/31631915/30037092-245f8fce-91c1-11e7-996f-8676304415e5.jpg)
![row-2-col-3](https://user-images.githubusercontent.com/31631915/30037093-2473ebae-91c1-11e7-8e77-74af7bbc00c3.jpg)
![row-2-col-4](https://user-images.githubusercontent.com/31631915/30037094-2474676e-91c1-11e7-9b75-fea26d7333ee.jpg)
![row-2-col-5](https://user-images.githubusercontent.com/31631915/30037097-247bfe3e-91c1-11e7-82da-b542c918acc4.jpg)
![row-2-col-6](https://user-images.githubusercontent.com/31631915/30037095-2478b94a-91c1-11e7-843c-66df079d8716.jpg)
![row-2-col-7](https://user-images.githubusercontent.com/31631915/30037096-247b682a-91c1-11e7-9522-545fbf0e04f7.jpg)
![row-2-col-8](https://user-images.githubusercontent.com/31631915/30037098-247e4112-91c1-11e7-8f5f-589b3b35e5a2.jpg)
![row-2-col-9](https://user-images.githubusercontent.com/31631915/30037100-24912066-91c1-11e7-9029-5ac13314d149.jpg)
![row-2-col-10](https://user-images.githubusercontent.com/31631915/30037099-2490acb2-91c1-11e7-8784-17c96643dad6.jpg)
![row-3-col-1](https://user-images.githubusercontent.com/31631915/30037101-2495df0c-91c1-11e7-8b76-7e9d19cc7dca.jpg)
![row-3-col-2](https://user-images.githubusercontent.com/31631915/30037102-249970b8-91c1-11e7-8fc7-9d0512c488f7.jpg)
![row-3-col-3](https://user-images.githubusercontent.com/31631915/30037103-2499beba-91c1-11e7-96ec-f3eeb113434f.jpg)
![row-3-col-4](https://user-images.githubusercontent.com/31631915/30037104-249c7646-91c1-11e7-83d3-5c9c04f209f4.jpg)
![row-3-col-5](https://user-images.githubusercontent.com/31631915/30037105-24ad435e-91c1-11e7-893a-09ffe5894b84.jpg)
![row-3-col-6](https://user-images.githubusercontent.com/31631915/30037106-24ad5fba-91c1-11e7-820b-21555310f5e8.jpg)
![row-3-col-7](https://user-images.githubusercontent.com/31631915/30037107-24b4110c-91c1-11e7-92f2-fe301b3c134e.jpg)
![row-3-col-8](https://user-images.githubusercontent.com/31631915/30037109-24b816ee-91c1-11e7-97f9-bceb4ddfdb1d.jpg)
![row-3-col-9](https://user-images.githubusercontent.com/31631915/30037108-24b7b352-91c1-11e7-917f-09fa6cc716a2.jpg)
![row-3-col-10](https://user-images.githubusercontent.com/31631915/30037110-24ba5102-91c1-11e7-83d5-b0952c5c6260.jpg)
![row-4-col-1](https://user-images.githubusercontent.com/31631915/30037112-24ca1e98-91c1-11e7-82af-cd712578e1ac.jpg)
![row-4-col-2](https://user-images.githubusercontent.com/31631915/30037111-24c9fac6-91c1-11e7-991b-79b2a466f926.jpg)
![row-4-col-3](https://user-images.githubusercontent.com/31631915/30037113-24d4804a-91c1-11e7-994f-7753285274e6.jpg)
![row-4-col-4](https://user-images.githubusercontent.com/31631915/30037114-24d64fb0-91c1-11e7-89f4-c3e6d594c7d5.jpg)
![row-4-col-5](https://user-images.githubusercontent.com/31631915/30037116-24da3396-91c1-11e7-8f68-9633179016cd.jpg)
![row-4-col-6](https://user-images.githubusercontent.com/31631915/30037115-24d944ae-91c1-11e7-928f-1dfc6f8d1d4d.jpg)
![row-4-col-7](https://user-images.githubusercontent.com/31631915/30037117-24e6e316-91c1-11e7-8c12-f54ba94ac643.jpg)
![row-4-col-8](https://user-images.githubusercontent.com/31631915/30037118-24e7290c-91c1-11e7-87b7-2f86a9d3e068.jpg)
![row-4-col-9](https://user-images.githubusercontent.com/31631915/30037119-24f1e86a-91c1-11e7-99af-ca00c57d7b2c.jpg)
![row-4-col-10](https://user-images.githubusercontent.com/31631915/30037120-24f409b0-91c1-11e7-8410-d6f0777ca710.jpg)
![row-5-col-1](https://user-images.githubusercontent.com/31631915/30037122-24fecc24-91c1-11e7-9a07-eaa1d2585599.jpg)
![row-5-col-2](https://user-images.githubusercontent.com/31631915/30037121-24f815fa-91c1-11e7-9f83-22bb2dde8248.jpg)
![row-5-col-3](https://user-images.githubusercontent.com/31631915/30037123-2502e7fa-91c1-11e7-8ce4-55b1b92d3310.jpg)
![row-5-col-4](https://user-images.githubusercontent.com/31631915/30037124-25047a0c-91c1-11e7-84d6-15d8dd641098.jpg)
![row-5-col-5](https://user-images.githubusercontent.com/31631915/30037125-250f8078-91c1-11e7-920c-eacdc3ed3a93.jpg)
![row-5-col-6](https://user-images.githubusercontent.com/31631915/30037126-2511a1a0-91c1-11e7-96bd-26e891abe638.jpg)
![row-5-col-7](https://user-images.githubusercontent.com/31631915/30037127-2516ba78-91c1-11e7-85fd-931f6eff5ac1.jpg)
![row-5-col-8](https://user-images.githubusercontent.com/31631915/30037128-251de3e8-91c1-11e7-87b8-de7abe00a491.jpg)
![row-5-col-9](https://user-images.githubusercontent.com/31631915/30037129-251f1b82-91c1-11e7-9028-f51e2247016d.jpg)
![row-5-col-10](https://user-images.githubusercontent.com/31631915/30037130-25215898-91c1-11e7-8d80-d5072bbf7d0b.jpg)
![row-6-col-1](https://user-images.githubusercontent.com/31631915/30037131-252d6f34-91c1-11e7-859c-32c650845a3c.jpg)
![row-6-col-2](https://user-images.githubusercontent.com/31631915/30037132-252e9cc4-91c1-11e7-91f6-dd4d227f4581.jpg)
![row-6-col-3](https://user-images.githubusercontent.com/31631915/30037133-25353d18-91c1-11e7-95c1-ab6ebed194cd.jpg)
![row-6-col-4](https://user-images.githubusercontent.com/31631915/30037135-253c837a-91c1-11e7-91c4-2aab14ff7b8d.jpg)
![row-6-col-5](https://user-images.githubusercontent.com/31631915/30037134-253b374a-91c1-11e7-81b4-0f35b8809ca7.jpg)
![row-6-col-6](https://user-images.githubusercontent.com/31631915/30037136-253dcd2a-91c1-11e7-912d-f24f785db0de.jpg)
![row-6-col-7](https://user-images.githubusercontent.com/31631915/30037137-254a4f46-91c1-11e7-9c09-aa9e0f891a75.jpg)
![row-6-col-8](https://user-images.githubusercontent.com/31631915/30037138-254bc09c-91c1-11e7-8b5c-4b06eded1d37.jpg)
![row-6-col-9](https://user-images.githubusercontent.com/31631915/30037139-25532c1a-91c1-11e7-8995-211bc0d9d09c.jpg)
![row-6-col-10](https://user-images.githubusercontent.com/31631915/30037140-25580a0a-91c1-11e7-9eb1-102a4d9e06d8.jpg)
![row-7-col-1](https://user-images.githubusercontent.com/31631915/30037142-255aceac-91c1-11e7-876d-351f609bb8d1.jpg)
![row-7-col-2](https://user-images.githubusercontent.com/31631915/30037141-255a5576-91c1-11e7-9924-3eee087df9bd.jpg)
![row-7-col-3](https://user-images.githubusercontent.com/31631915/30037143-25693eec-91c1-11e7-856d-ebb078435ec3.jpg)
![row-7-col-4](https://user-images.githubusercontent.com/31631915/30037144-256983ac-91c1-11e7-8da5-1fe25565e5d1.jpg)
![row-7-col-5](https://user-images.githubusercontent.com/31631915/30037145-2571394e-91c1-11e7-9bd4-1d8b70c7fef6.jpg)
![row-7-col-6](https://user-images.githubusercontent.com/31631915/30037146-2576d246-91c1-11e7-8d0f-a9d3a26f7dd2.jpg)
![row-7-col-7](https://user-images.githubusercontent.com/31631915/30037147-2576f05a-91c1-11e7-90d2-5021dadeb796.jpg)
![row-7-col-8](https://user-images.githubusercontent.com/31631915/30037148-2578c8f8-91c1-11e7-9320-afa0fd29f364.jpg)
![row-7-col-9](https://user-images.githubusercontent.com/31631915/30037149-25866a26-91c1-11e7-880e-3686c346ca5b.jpg)
![row-7-col-10](https://user-images.githubusercontent.com/31631915/30037150-2587cfce-91c1-11e7-862a-28aa86181da9.jpg)
![row-8-col-1](https://user-images.githubusercontent.com/31631915/30037151-258fa4ba-91c1-11e7-852f-ad1b4e2f05c7.jpg)
![row-8-col-2](https://user-images.githubusercontent.com/31631915/30037153-25943df4-91c1-11e7-8228-d02d8e149e75.jpg)
![row-8-col-3](https://user-images.githubusercontent.com/31631915/30037152-259356b4-91c1-11e7-86aa-a6f44d6624f8.jpg)
![row-8-col-4](https://user-images.githubusercontent.com/31631915/30037154-25979daa-91c1-11e7-94c3-2658d53087d5.jpg)
![row-8-col-5](https://user-images.githubusercontent.com/31631915/30037155-25a39e0c-91c1-11e7-9b25-079640a090bc.jpg)
![row-8-col-6](https://user-images.githubusercontent.com/31631915/30037156-25a615b0-91c1-11e7-8ef1-2f9070b84404.jpg)
![row-8-col-7](https://user-images.githubusercontent.com/31631915/30037157-25ae1788-91c1-11e7-9999-c76ddb7e4fc9.jpg)
![row-8-col-8](https://user-images.githubusercontent.com/31631915/30037158-25b00976-91c1-11e7-9564-6a8bfa68e2b6.jpg)
![row-8-col-9](https://user-images.githubusercontent.com/31631915/30037159-25b1d3dc-91c1-11e7-9595-cf0f21851a43.jpg)
![row-8-col-10](https://user-images.githubusercontent.com/31631915/30037160-25b5fc1e-91c1-11e7-98a1-cec4979dbddf.jpg)
![row-9-col-1](https://user-images.githubusercontent.com/31631915/30037161-25c16784-91c1-11e7-831a-eaa92c50c162.jpg)
![row-9-col-2](https://user-images.githubusercontent.com/31631915/30037162-25c351fc-91c1-11e7-89cf-5a05439e3921.jpg)
![row-9-col-3](https://user-images.githubusercontent.com/31631915/30037163-25cc9212-91c1-11e7-91a4-c03d2d1411f4.jpg)
![row-9-col-4](https://user-images.githubusercontent.com/31631915/30037164-25cca23e-91c1-11e7-8d7f-a504e73daf28.jpg)
![row-9-col-5](https://user-images.githubusercontent.com/31631915/30037165-25cef516-91c1-11e7-90e6-99ad52749bb3.jpg)
![row-9-col-6](https://user-images.githubusercontent.com/31631915/30037166-25d51194-91c1-11e7-8c7a-79b6786e5afb.jpg)
![row-9-col-7](https://user-images.githubusercontent.com/31631915/30037167-25e004fa-91c1-11e7-9d2e-2dc176b7c456.jpg)
![row-9-col-8](https://user-images.githubusercontent.com/31631915/30037168-25e21f10-91c1-11e7-8143-07f4b75504a0.jpg)
![row-9-col-9](https://user-images.githubusercontent.com/31631915/30037170-25eb3078-91c1-11e7-961e-bd1c6821e947.jpg)
![row-9-col-10](https://user-images.githubusercontent.com/31631915/30037169-25e8c3ec-91c1-11e7-99ad-4ca9597b311c.jpg)
![row-10-col-1](https://user-images.githubusercontent.com/31631915/30037171-25eb6610-91c1-11e7-8fd1-cb07e40b3956.jpg)
![row-10-col-2](https://user-images.githubusercontent.com/31631915/30037172-25f5185e-91c1-11e7-8559-aecf3c26f3a6.jpg)
![row-10-col-3](https://user-images.githubusercontent.com/31631915/30037173-25fd6338-91c1-11e7-9fee-7dede38865b7.jpg)
![row-10-col-4](https://user-images.githubusercontent.com/31631915/30037174-26018b0c-91c1-11e7-81b3-9e4f24fbd818.jpg)
![row-10-col-5](https://user-images.githubusercontent.com/31631915/30037175-26061654-91c1-11e7-959e-9feb339236d6.jpg)
![row-10-col-6](https://user-images.githubusercontent.com/31631915/30037177-26094ec8-91c1-11e7-85f9-19492236be1b.jpg)
![row-10-col-7](https://user-images.githubusercontent.com/31631915/30037176-2607bca2-91c1-11e7-8db4-185a7474460b.jpg)
![row-10-col-8](https://user-images.githubusercontent.com/31631915/30037178-26142456-91c1-11e7-86a7-21b19c55c880.jpg)
![row-10-col-9](https://user-images.githubusercontent.com/31631915/30037179-261d92b6-91c1-11e7-830c-e84061472779.jpg)
![row-10-col-10](https://user-images.githubusercontent.com/31631915/30037180-261fbf0a-91c1-11e7-8cfb-cca881fe8376.jpg)

**Comment by overfrantic** [comment]
![startup-layer](https://user-images.githubusercontent.com/31631915/30037472-cdaed40c-91c3-11e7-8368-dc57dbb6908b.jpg)

**Comment by overfrantic** [comment]
body {
		  background:#000 url(<?=$coreAddr?>i/bright-squares.png);
		  margin:0px auto;
		  padding:0px;
		  font-size:100%;
		  font-weight:300;
		  direction:ltr;
		  font-family:-apple-system,BlinkMacSystemFont,Roboto,'Open Sans','Helvetica Neue',sans-serif;
		  line-height:1 !important;
		  -webkit-font-smoothing:subpixel-antialiased;
		  -moz-osx-font-smoothing:auto;
		  outline:none;
		  letter-spacing:0px;
		  width:1000px;
		  height:820px
	  }

	  img{display: block;}
	  
	  .bebas{font-family:'Bebas'}
	  .bebasB{font-family:'BebasB'}
	  
      .centered {margin:0 auto}
      .fl {float:left} .fr {float:right} .cl {clear:both} .cl1 {clear:both;height:1px} .cl2 {clear:both;height:2px} .cl3 {clear:both;height:3px} .cl4 {clear:both;height:4px} .cl5 {clear:both;height:5px} .cl10 {clear:both;height:10px} .cl15 {clear:both;height:15px} .cl20 {clear:both;height:20px} .cl100 {clear:both;height:100px} .cl150 {clear:both;height:150px} .cp {cursor:pointer}
      .bb {box-sizing:border-box} .pr {position:relative;}
      div {margin:0px;padding:0px}
      .br1 {border-radius:1px}
      .pt1 {padding-top:1px}
      .ml3 {margin-left:3px} .ml5 {margin-left:5px} .ml9 {margin-left:9px} .ml10 {margin-left:10px} .ml15 {margin-left:15px} .ml20 {margin-left:20px}
      .mr5 {margin-right:5px} .mr10 {margin-right:10px} .mr15 {margin-right:15px} .mr20 {margin-right:20px}
      .mb1 {margin-bottom:1px} .mb3 {margin-bottom:3px}
      .mt1 {margin-top:1px} .mt2 {margin-top:2px} .mt3 {margin-top:3px} .mt4 {margin-top:4px} .mt5 {margin-top:5px} .mt6 {margin-top:6px} .mt10 {margin-top:10px} .mt15 {margin-top:15px}
      .fc0 {color:#000} .fc3 {color:#333} .fcF {color:#FFF} .fcC {color:#CCC} .fcA {color:#AAA} .fc7 {color:#777} .fc5 {color:#555} .fcGOLD {color:#d9bb1a} .fcR {color:#D00000}
      .fs40 {font-size:40%} .fs50 {font-size:50%} .fs60 {font-size:60%} .fs65 {font-size:65%} .fs70 {font-size:70%} .fs75 {font-size:75%} .fs80 {font-size:80%} .fs90 {font-size:90%} .fs100 {font-size:100%} .fs105 {font-size:105%} .fs110 {font-size:110%} .fs120 {font-size:120%} .fs130 {font-size:130%} .fs140 {font-size:140%} .fs150 {font-size:150%} .fs160 {font-size:160%} .fs170 {font-size:170%} .fs180 {font-size:180%}
      .fwb{font-weight:700;} .fwn{font-weight:normal}
      .dp{display:block}
      
      a {font-weight:bold}
	  a.simple {font-weight:bold;color:#a6bc59;text-decoration:underline}
	  a.simple:hover {color:#FFF;text-decoration:none}
	  a.simpld {font-weight:bold;color:#000;text-decoration:underline}
	  a.simpld:hover {color:#000;text-decoration:none}

	  #w-top {z-index:10000;width:1000px;background:#000;cursor:pointer}

	  .m-b {padding:4px 7px;cursor:pointer;font-size:60%;text-align:center;font-weight:bold;color:#FFF;background:#333;border-radius:1px;text-decoration:none}
      .m-b:hover {padding:4px 7px;cursor:pointer;font-size:60%;text-align:center;font-weight:bold;border-radius:1px;text-decoration:none;background:#1f8fc9;color:#FFF}
	  .m-b_active {padding:4px 7px;cursor:pointer;font-size:60%;text-align:center;font-weight:bold;border-radius:1px;text-decoration:none;background:#1f8fc9;color:#FFF}
	  .m-b_disabled {padding:4px 7px;cursor:pointer;font-size:60%;text-align:center;font-weight:bold;color:#555;background:#333;border-radius:1px;text-decoration:none}

	   .statusbar {color:#FFF;padding:4px 7px;}
	   .ap {position:absolute;background:#D00;border-radius:100px;height:9px;width:9px;cursor:pointer;opacity:1;}
	   .apt {color:#FFF;text-shadow:black 0px 0px 1px;position:absolute;width:100px}
	   .btnCreate { padding:5px 10px;cursor:pointer;font-size:90%;text-align:center;font-weight:bold;color:#FFF;background:#1f8fc9;border-radius:1px;text-decoration:none }
	   .btnChoose { padding:3px 7px;cursor:pointer;font-size:60%;text-align:center;font-weight:bold;color:#AAA;background:#333;border-radius:1px;text-decoration:none;margin-right:1px }
	   .btnChoose-h { background:#1f8fc9;color:#FFF }
	   
	   .nvar {width:20px;height:20px;z-index:1000;cursor:pointer}
       .mpc {position:absolute;top:0px;left:0px;width:16200px;height:6500px;z-index:100}
	   .close-b {position:absolute;top:5px;right:5px;cursor:pointer;width:12px;height:12px}
	   
	   svg path, svg rect{ fill: #00baff; }
	   
	   .a1{position:absolute;top:0px;left:0px;background:#EFEFEF;z-index:100000;width:1000px;height:817px;overflow:hidden}
	   .a2{z-index:100001;position:absolute;top:0px;left:0px;width:1000px;height:900px}
	   .a3{position:absolute;bottom:20px;right:20px;z-index:100002}
	   .a4{width:1000px;overflow:hidden}
.a5{color:#FFF;cursor:default;background:#96165e}
.a6{cursor:default;background:#96165e}
.a7{cursor:pointer;background:#686868}
.a8{cursor:pointer;background:#bb901b}
.a9{cursor:pointer;background:#7aa316}
.b1{cursor:pointer;width:92px;height:17px}
.b2{display:none;position:absolute;top:0px;left:0px;padding:4px;z-index:10001;width:1000px;background:#8ba146;cursor:pointer;text-align:center}
.b2a{background:#dc2b40;}
.b3{width:1000px;height:800px;overflow:hidden;background:#99DD00}
#dlgLayerBlack{display:none;position:absolute;top:0px;left:0px;width:1100px;height:1100px;background:#000;z-index:10;opacity:0.85}
.b4{position:absolute;top:5px;left:125px;z-index:12000;display:none;}
.b5{position:absolute;top:45px;left:25px;width:200px;z-index:12000;display:none;}
.b6{position:absolute;top:5px;left:195px;z-index:12000;display:none;}
.b7{position:absolute;top:45px;left:95px;width:200px;z-index:12000;display:none;}
.b8{position:absolute;top:5px;left:515px;z-index:12000;display:none;}
.b9{position:absolute;top:45px;left:415px;width:200px;z-index:12000;display:none;}
.c0{display:none;position:absolute;top:50px;left:300px;background:#000;width:400px;z-index:10000;overflow:hidden;padding-bottom:10px}
.c0a{left:200px;width:600px}
.c0b{left:250px;width:500px}
.c1{width:400px;height:196px}
.c2{padding:10px;background:#111;text-align:center}
.c3{padding:10px}
.c4{width:100%;background:#333;border:0px;padding:5px 10px}
.c4a{padding:0px 10px}
.c4b{padding:5px}
.c5{height:87px;padding-top:30px;text-align:center;text-shadow:black 0px 0px 1px;}
.c5a{height:85px}
.c6{height:400px;overflow:auto}
.c7{display:none}
.w50p{width:50%}
.c8{width:70%;background:#333;border:0px;padding:4px 10px;padding-bottom:5px}
.c8a{width:30%}
.c8b{width:33%}
.c9{width:50%;padding:0px 10px}
.d0{display:none;width:100%;height:553px;overflow:hidden}
.d0a{padding:2px;background:#222}
.d0b{background:#111}
.d1{width:100%;padding:10px;height:500px;overflow:hidden}
.d1a{background:#7f9141;padding:3px;border-bottom:1px solid #444}
.d1b{background:#222}
.d1c{width:30px}
.d1d{width:170px;overflow:hidden}
.d1e{width:70px;text-align:right}
.d1f{width:60px;text-align:right;margin-right:8px}
.d2{height:105px;padding-top:40px;text-align:center;text-shadow:black 0px 0px 1px;}
.d3{width:20px}
.d4{width:180px;overflow:hidden}
.d5{width:60px}
.d6{width:80px;text-align:right;margin-right:8px}
.d7{width:60px;text-align:right}
.d8{width:100%;height:100%;overflow:hidden;background:#D00;z-index:1}
.d9{display:none;position:absolute;top:0px;left:0px}
.e0{position:absolute;top:5px}
.e0a{left:490px}
.e0b{right:5px}
.e1{position:absolute;bottom:5px}
.e1a{left:5px}
.e2{position:absolute;top:390px}
.e3{display:none;z-index:120}
.e4{margin-top:-1000px;margin-left:-9000px}
.e5{width:892px;background:#000;padding:0px 0px;padding-left:10px}
